# 오류 전달 방법
<br/>

오류가 발생하면 일반적으로 더 높은 계층으로 오류를 알려야 한다.
오류로부터 복구할 수 없는 경우 이는 일반적으로 프로그램의 훨씬 더 높은 계층에서 실행을 중지하고, 오류를 기록하거나 전체 프로그램의 실행을 종료하는 것을 의미한다.
오류로부터의 복구가 잠재적으로 가능한 경우, 일반적으로 즉시 호출하는 쪽(또는 호출 체인에서 한두 수준 위의 호출자)에 오류를 알려 정상적으로 처리할 수 있도록 해야 한다.

이 작업을 수행하는 방법은 여러 가지가 있으며, 사용하는 언어가 지원하는 오류 처리 기능에 따라 가능한 방법이 달라진다. 오류를 알리는 방법은 크게 두 가지 종류로 나뉜다.
- **명시적 방법**
  - 코드를 직접 호출한 쪽에서 오류가 발생할 수 있음을 인지할 수밖에 없도록 한다.
    그것을 처리하든, 이전 호출자에게 전달하든, 아니면 그냥 무시하든 간에 어떻게 처리할지는 호출하는 쪽에 달려 있다.
    하지만 무엇을 하든 그것은 적극적인 선택의 결과다. 오류가 발생할 가능성이 코드 계약의 명확한 부분에 나타나 있기 때문에 오류를 모르고 넘어갈 수 있는 방법은 거의 없다.
- **암시적 방법**
  - 코드를 호출하는 쪽에 오류를 알리지만, 호출하는 쪽에서 그 오류를 신경 쓰지 않아도 된다.
    오류가 발생할 수 있음을 알기 위해서는 문서나 코드를 읽는 등의 적극적인 노력이 필요하다. 문서에 오류가 언급되어 있다면 코드 계약의 숨겨진 세부 조항이다.
    가끔 오류가 여기서조차 언급되지 않을 때도 있는데, 이 경우엔 오류가 계약 내용에 전혀 없는 것이 된다.

강조하자면, 이 범주는 코드를 사용하는 개발자 관점에서 오류 발생 가능성이 명시적인지 혹은 암시적인지를 말하는 것이다.
이것은 오류가 결국 요란하게 실패할지 아니면 조용히 실패할지에 대한 것이 아니다.
호출하는 쪽에서 (명시적인 기법을 통해) 알아야 할 경우를 인지하게끔 하거나 (암묵적 기법을 통해) 할 수 있는 것이 아무것도 없는 상황이라면
이런 상황을 처리해야 하는 부담에서 벗어나게 하는 것이다.

다음 표에 명시적 그리고 암묵적인 오류 전달 기법의 몇 가지 예가 나열되어 있다.

#### [명시적 및 암묵적인 오류 전달 기법]
||명시적 오류 전달 기법|암시적 오류 전달 기법|
|:---|:---|:---|
|**코드 계약에서의 위치**|명확한 부분|세부 조항 혹은 아예 없음|
|**호출하는 쪽에서 오류 발생<br/>가능성에 대해 아는가?**|그렇다.|알 수도 있고 모를 수도 있다.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|**기법의 예**|검사 예외<br/>널 반환 유형 (널 안전성의 경우)<br/>옵셔널 반환 유형<br/>리절트 반환 유형<br/>아웃컴 반환 유형 (반환값 확인이 필수인 경우)<br/>스위프트 오류|비검사 예외<br/>매직값 반환 (피해야 한다)<br/>프로미스 또는 퓨처<br/>어서션<br/>체크 (구현에 따라 달라짐)<br/>패닉|

위 표에 열거된 기법 중 일부를 살펴볼 텐데, 사용 방법에 대한 예와 해당 기법이 왜 명시적 혹은 암묵적인지 이유를 설명한다.
<br/>

## 1. 요약: 예외
많은 프로그래밍 언어들은 예외라는 개념을 가지고 있다. 이것은 코드에서 오류나 예외적인 상황이 발생한 경우 이를 전달하기 위한 방법으로 고안되었다.
예외가 발생했을 때 콜 스택을 거슬러 올라가는데 예외를 처리하는 코드를 만나거나, 더 이상 올라칼 콜 스택이 없을 때까지 그렇게 한다.
더 이상 올라갈 콜 스택이 없는 경우에는 오류 메시지를 출력하고 프로그램이 종료된다.

예외는 일반적으로 충분한 기능을 가진 클래스로 구현된다.
보통 프로그래밍 언어는 즉시 사용할 수 있는 예외에 대한 클래스를 제공하지만 개발자들은 자신의 요구 사항에 따른 맞춤형 예외 처리를 위해
오류에 대한 정보를 자유롭게 정의하고 캡슐화할 수 있다.

자바는 **검사 예외**(checked exception)와 **비검사 예외**(unchecked exception)의 개념을 모두 가지고 있다.
예외를 지원하는 대부분의 주요 언어는 비검사 예외만 가지고 있으므로 자바 이외의 거의 모든 언어에서 예외라는 용어는 일반적으로 비검사 예외를 의미한다.

## 2. 명시적 방법: 검사 예외
컴파일러는 검사 예외에 대해 호출하는 쪽에서 예외를 인지하도록 강제적으로 조치하는데,
호출하는 쪽에서는 **예외 처리를 위한 코드를 작성**하거나 **자신의 함수 시그니처에 해당 예외 발생을 선언**해야 한다.
따라서 검사 예외를 사용하는 것은 오류를 전달하기 위한 명시적인 방법이다.

### 검사 예외를 사용한 오류 전달
서로 다른 오류 전달 기법을 설명하고 비교하기 위해, 제곱근을 계산하는 함수를 예로 사용해보자.
이 함수의 입력값으로 음수가 제공된다면, 이것은 어떻게든 알려야 하는 오류다.
대부분의 프로그래밍 언어에는 제곱근을 계산하는 함수가 이미 내장되어 있기 때문에 실제로 이런 함수를 작성할 일은 없을 것이다.
하지만 이 함수는 오류 전달 기법을 설명하기 위한 간단하고 좋은 예다.

예제 4.8은 이 함수에 음수가 입력으로 들어오면 NegativeNumberException이라는 검사 예외를 발생시키는 경우를 보여 준다.
자바에서 Exception 클래스를 확장하면 확장된 클래스는 검사 예외가 되는데 이에 대한 자바 코드가 예제 4.8에 나와 있다.
NegativeNumberException은 오류를 전달할 뿐만 아니라 오류를 초래한 값도 멤버 변수로 가질 수 있는데 이 경우 디버깅에 도움이 된다.
getSqureRoot() 함수의 시그니처에는 throws NegativeNumberException이 포함되어 있고 이것은 이 함수가 검사 예외를 발생시킬 수 있다는 것을 의미한다.
throws NegativeNumberException이 없으면 코드가 컴파일되지 않는다.

#### [예제 4.8] 검사 예외 발생
```java
class NegativeNumberException extends Exception {  // 검사 예외의 구체적 유형임을 나타내는 클래스
  private final Double erroneousNumber;  // 오류를 유발한 숫자를 캡슐화해서 추가 정보를 제공

  NegativeNumberException(Double erroneousNumber) {
    this.erroneousNumber = erroneousNumber;
  }

  Double getErroneousNumber() {
    return erroneousNumber;
  }
}

Double getSquareRoot(Double value)
    throws NegativeNumberException {  // 함수는 검사 예외를 발생시킬 수 있음을 선언해야 한다.
  if (value < 0.0) {
    throw new NegativeNumberException(value);  // 오류가 있을 시 검사 예외를 발생시킨다.
  }
  return Math.sqrt(value);
}
```

### 검사 예외 처리
getSquareRoot() 함수를 호출하는 코드는 NegativeNumberException 예외를 처리하거나 함수 시그니처에 이 예외를 발생시킬 수 있음을 표시해야 한다.

예제 4.9 코드의 함수는 getSquareRoot()를 호출하고 그 결과를 UI에 표시한다.
이 함수는 NegativeNumberException이 발생하면 이 예외를 포착하고 오류를 유발한 숫자를 설명하는 메시지를 표시한다.

#### [예제 4.9] 검사 예외의 포착
```java
void displaySquareRoot() {
  Double value = ui.getInputNumber();
  try {
    ui.setOutput("Square root is: " + getSquareRoot(value));
  } catch (NegativeNumberException e) {  // 예외를 발생시키면 이 예외를 포착한다.
    ui.setError("Can`t get square root of negative number: " +
        e.getErroneousNumber());  // 예외 객체 안에 들어 있는 오류에 대한 정보를 표시한다.
  }
}
```
displaySquareRoot() 함수가 NegativeNumberException을 포착하지 않는 경우에는 이 함수의 시그니처에 이 예외가 발생할 수 있음을 선언해야 한다.
이 경우에는 이 예외가 발생하는 경우의 처리를 자신이 하지 않고 displaySquareRoot() 함수를 호출하는 코드에게 맡기는 것이 된다.

#### [예제 4.10] 검사 예외를 포착하지 않음
```java
void displaySquareRoot() throws NegativeNumberException {  / * NegativeNumberException이 
  Double value = ui.getInputNumber();                        * displaySquareRoot() 함수의 시그니처에 선언되어 있다.
  ui.setOutput("Square root is: " + getSquareRoot(value));   * /
}
```
displaySquareRoot() 함수가 NegativeNumberException 예외를 포착하지도 않고, 자신의 함수 시그니처에 선언하지도 않으면 코드는 컴파일되지 않는다.
호출하는 쪽에서는 어떤 형태로든 해당 오류를 강제적인 방식으로 인지할 수밖에 없기 때문에 검사 예외는 오류를 전달하는 명시적 방법이 된다.

## 3. 암시적 방법: 비검사 예외
비검사 예외를 사용하면 다른 개발자들은 코드가 이 예외를 발생시킬 수 있다는 사실을 전혀 모를 수 있다.
이 경우에는 함수에서 어떤 예외를 발생시키는지 문서화하는 것이 바람직하지만 개발자가 문서화하는 것을 잊어버릴 때가 있다.
설사 문서화를 하더라도 이것은 코드 계약의 세부 조항이다. 앞에서 살펴본 것처럼 세부 조항은 코드 계약 내용을 전달하는 데 있어 신뢰할 만한 방법이 아닐 때가 많다.
따라서 비검사 예외는 오류가 발생할 수 있다는 것을 호출하는 쪽에서 인지하리라는 보장이 없기 때문에 오류를 암시적으로 알리는 방법이다.

### 비검사 예외를 사용한 오류 전달
예제 4.11 코드는 getSquareRoot() 함수와 NegativeNumberException을 보여주지만 이전 하위 절의 예제 코드와는 달리 NegativeNumberException이 비검사 예외로 변경되었다.
앞서 언급한 바와 같이 대부분의 언어에서 예외는 비검사 예외지만 자바에서는 RuntimeException 클래스를 확장하는 예외 클래스는 비검사 예외이고 이에 대한 자바 코드가
예제 4.11에 나와 있다. 이제 getSquareRoot() 함수는 예외를 발생시킬 수 있음을 선언할 필요가 없다.
이 함수에 대한 문서에 NegativeNumberException에 대해 언급할 수 있는데 권장사항이지 강제사항은 아니다.

#### [예제 4.11] 비검사 예외 발생
```java
class NegativeNumberException extends RuntimeException {  // 비검사 예외의 구체적인 유형임을 나타내는 클래스
  private final Double erroneousNumber;

  NegativeNumberException(Double erroneousNumber) {
    this.erroneousNumber = erroneousNumber;
  }

  Double getErroneousNumber() {
    return erroneousNumber;
  }
}

/**
* @throws NegativeNumberException 값이 음수일 경우 --> 어떤 종류의 비검사 예외가 발생할 수 있는지 문서화하는 것이 권장된다
*/
Double getSquareRoot(Double value) {
  if (value < 0.0) {
    throw new NegativeNumberException(value);  // 오류에 대해 비검사 예외를 발생시킨다.
  }
  return Math.sqrt(value);
}
```

### 비검사 예외 처리
getSquareRoot() 함수를 호출하는 다른 함수는 NegativeNumberException에 대해 이전 예와 동일한 방식으로 예외를 포착하고 처리할 수 있다.

#### [예제 4.12] 비검사 예외 처리
```java
void displaySquareRoot() {
  Double value = ui.getInputNumber();
  try {
    ui.setOutput("Square root is: " + getSquareRoot(value));
  // getSquareRoot()가 NegativeNumberException 예외를 발생시키면 이 예외를 포착하고 처리한다.
  } catch (NegativeNumberException e) { 
    ui.setError("Can`t get square root of negative number: " + e.getErroneousNumber());
  }
}
```
중요한 것은 getSquareRoot()를 호출하는 함수가 예외를 확인하고 처리하지 않아도 된다는 점이다.
예외를 포착해서 처리하지 않는 경우 자체 함수 시그니처에 선언하지 않아도 되고 심지어 문서화하지 않아도 된다.
예제 4.13 코드는 NegativeNumberException을 처리하거나 선언하지 않는 displaySquareRoot() 함수를 보여준다.
NegativeNumberException 예외는 비검사 예외이기 때문에 이 코드는 문제없이 컴파일된다.
getSquareRoot()가 NegativeNumberException 예외를 발생시키면, 이 예외를 처리하는 코드를 만날 때까지 계속 올라가거나, 끝까지 그 코드가 없으면 프로그램이 종료된다.

#### [예제 4.13] 비검사 예외를 처리하지 않음
```java
void displaySquareRoot() {
  Double value = ui.getInputNumber();
  ui.setOutput("Square root is: " + getSquareRoot(value));
}
```
이 코드에서 알 수 있듯이 비검사 예외를 발생시키는 함수를 호출하는 쪽에서는 예외가 발생할 수 있다는 사실을 전혀 몰라도 된다.
이로 인해 비검사 예외는 오류를 암시적으로 전달하는 방법이다.

## 4. 명시적 방법: 널값이 가능한 반환 유형
함수에서 널값을 반환하는 것은 특정값을 계산하거나 얻는 것이 불가능함을 나타내기 위한 효과적이고 간단한 방법이다.
사용 중인 언어가 널 안전성을 지원하는 경우 널값이 반환될 수 있다는 것을 호출하는 쪽에서 강제적으로 인지하고, 그에 따라 처리할 수밖에 없다.
따라서 (널 안전성을 지원할 때) 널값이 가능한 반환 유형을 사용하는 것은 오류를 전달하기 위한 명시적인 방법이다.

널 안전성을 지원하지 않는 언어를 사용하는 경우 옵셔널 반환 유형을 사용하는 것이 좋다.

### 널값을 이용한 오류 전달
예제 4.14 코드는 getSquareRoot() 함수를 보여주는데 입력값이 음수일 경우 널값을 반환하도록 수정되었다.
널값을 반환할 때의 한 가지 문제점은 오류가 발생한 이유에 대한 정보를 제공하지 않기 때문에 널값이 의미하는 바를 설명하기 위해 주석문이나 문서를 추가해야 한다.

#### [예제 4.14] 널값 반환
```java
// 제공되는 값이 음수이면 널을 반환한다. ---> 언제 널값이 반환되는지 설명하는 주석문
Double? getSquareRoot(Double value) {  // 'Double?'에서 ?는 널값이 반환될 수 있음을 나타낸다.
  if (value < 0.0) {
    return null;  // 오류가 발생하면 널값이 반환된다.
  }
  return Math.sqrt(value);
}
```

### 널값 처리
이 책에서 사용하는 의사코드는 널 안전성을 지원하기 떄문에 호출하는 쪽에서 getSquareRoot()에 의해 반환된 값을 사용하기 전에 널인지 반드시 확인해야 한다.
다음 예제 코드는 displaySquareRoot() 함수를 보여주는데 이번에는 널값이 가능한 반환 유형을 처리한다.

#### [예제 4.15] 널 처리
```java
void displaySquareRoot() {
  Double? squareRoot = getSquareRoot(ui.getInputNumber());
  if (squareRoot == null) {  // getSquareRoot()의 반환값이 널값인지 확인해야 한다.
    ui.setError("Can`t get square root of a negative number");
  } else {
    ui.setOutput("Square root is: " + squareRoot);
  }
}
```
호출하는 쪽에서 널값 여부를 강제로 확인해야 한다는 것은 엄밀히 말해서 사실이 아니다.
반환되는 값을 널이 아닌 값으로 타입 변환을 할 수 있으며, 이것은 여전히 적극적인 결정이다. 타입 변환 시 값이 널인 경우를 처리할 수밖에 없다.

## 5. 명시적 방법: 리절트 반환 유형
널값이나 옵셔널 타입을 반환할 때의 문제 중 하나는 오류 정보를 전달할 수 없다는 것이다.
호출자에게 값을 얻을 수 없음을 알릴 뿐만 아니라 값을 얻을 수 없는 이유까지 알려주면 유용하다. 이러한 경우에는 리절트(result) 유형을 사용하는 것이 적절할 수 있다.

스위프트(Swift), 러스트(Rust), F#과 같은 언어들은 리절트 유형을 지원하고 사용하기 쉽도록 편한 구문을 제공한다.
어떤 프로그래밍 언어에서도 자신만의 리절트 유형을 만들 수 있지만, 프로그래밍 언어에서 기본적으로 지원되는 구문 없이는 이들을 사용하는 것이 조금 번거로울 수 있다.

예제 4.16 코드는 리절트 유형을 지원하지 않는 언어에서 이것을 정의하는 방법에 대한 기본적인 예를 보여준다.

#### [예제 4.16] 간단한 리절트 유형
```java
class Result<V, E> {  // 제네릭/템플릿 유형이 사용되기 때문에 이 클래스는 어떤 유형의 값이나 오류에 대해서도 사용할 수 있다.
  private final Optional<V> value;
  private final Optional<E> error;

  private Result(Optional<V> value, Optional<E> error) {  / * 생성자는 프라이빗이기 때문에 호출하는 쪽에서
    this.value = value;                                     * 정적 팩토리 함수를 쓸 수밖에 없다.
    this.error = error;                                     * /
  }

/******************************************************************************************************/
/**
* 정적 팩토리 함수. 
* 이 클래스는 값이나 오류 중 한 가지로만 인스턴스를 만들 수 있고 둘 다 가능한 인스턴스는 생성할 수 없다.
*/
  static Result<V, E> ofValue(V value) {
    return new Result(Optional.of(value), Optional.empty());
  }

  static Result<V, E> ofError(E error) {
    return new Result(Optional.empty(), Optional.of(error));
  }
/******************************************************************************************************/

  Boolean hasError() {
    return error.isPresent();
  }

  V getValue() {
    return value.get();
  }

  E getError() {
    return error.get();
  }
}
```

#### [리절트 유형 구현]
```
리절트 유형을 실제로 구현하려면 예제 4.16의 코드보다 더 정교해야 한다.
예를 들어 열거형 같은 언어 구성 요소를 활용하고 결과를 반환하기 위한 헬퍼 함수를 제공해야 한다.

러스트 및 스위프트에서 리절트 유형을 어떻게 구현하는지 살펴보면 이에 대해 이해하는 데 도움이 될 것이다.
- https://doc.rust-lang.org/beta/core/result/enum.Result.html
- https://developer.apple.com/documentation/swift/result
```

(언어 자체에서 지원하지 않기 때문에) 자신만의 리절트 유형을 정의한다면, 이것이 제대로 사용될지 여부는 다른 개발자가 리절트 유형을 사용하는 방법에 얼마나 익숙해지는가에 달려있다.
이전에 리절트 유형을 접해본 적이 없는 개발자가 부지런하게 이 코드를 재빨리 파악하더라도 getValue()를 호출하기 전에 hasError() 함수를 통해 오류를 확인하지 않는다면
리절트 유형이 무용지물이 된다.

언어가 리절트 유형을 지원하거나 혹은 (자신만의 리절트 유형을 정의할 때) 다른 개발자들이 그 유형에 익숙하다고 가정하면,
리절트 유형을 반환 유형으로 사용하는 것은 오류가 발생할 수 있다는 점을 분명히 하는 것이 된다.
따라서 리절트 반환 유형을 사용하는 것은 오류를 알리는 명시적인 방법이다.

### 리절트 유형을 이용한 전달
예제 4.17 코드에서 getSquareRoot() 함수는 리절트 유형을 반환하도록 수정되었다.
NegativeNumberError은 사용자 정의 오류이며, getSquareRoot()의 반환 유형을 보면 이 오류가 잠재적으로 발생할 수 있음을 의미한다.
NegativeNumberError는 오류에 대한 추가 정보, 즉 오류를 일으킨 잘못된 값을 가지고 있다.

#### [예제 4.17] 리절트 유형 반환
```java
class NegativeNumberError extends Error {  // 오류의 구체적 유형을 나타내는 클래스
  private final Double erroneousNumber;

  NegatieNubmerError(Double erroneousNumber) {  // 추가 정보, 즉 오류를 유발한 값을 갖는다.
    this.erroneousNumber = erroneousNubmer;
  }

  Double getErroneousNumber() {
    return erroneousNumber;
  }
}

/**
* 리절트 유형을 통해 NegativeNumberError가 발생할 수 있다는 것을 알 수 있다.
*/
Result<Double, NegativeNumberError> getSquareRoot(Double value) {
  if (value < 0.0) {
    return Result.ofError(new NegativeNumberError(value));  // 오류가 발생하면 오류 리절트가 반환된다.
  }
  return Result.ofValue(Math.sqrt(value));  // 함수의 결괏값은 리절트 유형에 들어 있다.
}
```

### 리절트 처리
getSquareRoot() 함수를 호출하는 개발자는 이 함수가 반환하는 값이 리절트 유형이라는 것을 명백히 알 수 있다.
리절트 유형을 사용하는 것이 익숙하다고 가정하면, 오류가 발생했는지 확인하기 위해 먼저 hasError()를 호출해야 하고,
오류가 발생하지 않았다는 것을 확인하고 나면 getValue()를 호출하여 결괏값을 얻을 수 있다는 것을 알 것이다.
오류가 발생한 경우라면 반환된 객체의 getError()를 호출해서 세부 정보를 얻을 수 있다. 다음 예제는 이것을 보여준다.

#### [예제 4.18] 리절트 유형 반환
```java
void displaySquareRoot() {
  Result<Double, NegativeNumberError> squareRoot =
      getSquareRoot(ui.getInputNumber());
  if (squareRoot.hasError()) {  // squareRoot 결괏값은 오류를 확인해야 한다.
    ui.setError("Can`t get square root of a negative number: " +
        squareRoot.getError().getErroneousNumber());  // 자세한 오류 정보를 사용자게에 보여준다.
  } else {
    ui.setOutput("Square root is: " + squareRoot.getValue());
  }
}
```

#### [좀 더 좋은 구문]
```
리절트 유형을 지원하는 프로그래밍 언어는 예제 4.18에서 보이는 것보다 더 간결한 구문을 갖는다.
또한, 자신만의 리절트 유형을 구현할 때 헬퍼 함수를 추가해서 좀 더 나은 제어 흐름을 만들 수도 있는데,
예를 들어 러스트의 and_then() 함수가 있다. (https://mng.bz/Jv5P)
```

## 6. 명시적 방법: 아웃컴 반환 유형
어떤 함수들은 값을 반환하기보다는 단지 무언가를 수행하고 값을 반환하지는 않는다.
어떤 일을 하는 동안 오류가 발생할 수 있고 그것을 호출한 쪽에 알리고자 한다면, 함수가 수행한 동작의 결과를 나타내는 값을 반환하도록 함수를 수정하는 것이 한 가지 방법이 될 수 있다.
아웃컴 반환 유형을 반환할 때 호출하는 쪽에서 반환값을 강제적으로 확인해야 한다면 이것은 오류를 알리는 명백한 방법이다.

### 아웃컴을 이용한 오류 전달
예제 4.19는 채널에 메시지를 보내는 코드를 보여준다. 메시지는 채널이 열러 있는 경우에만 보낼 수 있다. 채널이 열리지 않으면 오류다.
sendMessage() 함수는 불리언값을 반환함으로써 오류가 발생했음을 전달한다. 메시지가 전송되면 참을, 오류가 발생하면 거짓을 반환한다.

#### [예제 4.19] 아웃컴 반환
```java
Boolean sendMessage(Channel channel, String message) {  // 이 함수는 불리언값을 반환한다.
  if (channel.isOpen()) {
    channel.send(message);
    return true;  // 메시지가 전송되면 참을 반환한다.
  }
  return false;  // 오류가 발생하면 거짓을 반환한다.
}
```
좀 더 복잡한 시나리오를 구현해야 한다면, 단순한 불리언보다 더 정교한 아웃컴 유형을 사용하는 것이 더 적절할 수 있다.
가능한 결과 상태가 두 개 이상 있거나, 참과 거짓이 무엇을 의미하는지 분명하지 않은 경우에 열거형을 사용하면 유용하다.
더 자세한 정보가 필요하다면 이것을 캡슐화하기 위해 전체 클래스를 정의하는 것도 또 다른 방법이다.

### 아웃컴 처리
불리언값을 반환 유형으로 사용하는 예에서 결과를 처리하는 것은 아주 간단하다. 함수 호출은 If-else 문에 두고 각 분기에 적절한 처리 로직을 두면 된다.
다음 예제는 채널에서 'hello' 메시지를 보내고 메시지가 전송되었는지 여부를 UI에 보여주는 코드다.

#### [예제 4.20] 아웃컴 처리
```java
void sayHello(Channel channel) {
  if (sendMessage(channel, "hello")) {
    ui.setOutput("Hello sent");  // 성공한 경우 처리
  } else {
    ui.setError("Unable to send hello");  // 실패한 경우 처리
  }
}
```

### 아웃컴이 무시되지 않도록 보장
아웃컴 반환 유형에 대한 문제점 중 하나는 호출하는 쪽에서 반환값을 무시하거나 함수가 값을 반환한다는 사실조차 인식 못할 수 있다는 점이다.
이로 인해 아웃컴 반환 유형은 오류를 알리는 명시적 방법으로서 한계가 있다.

다음 예제는 이에 대해 호출하는 쪽의 코드를 보여준다.
sendMessage()로부터의 결과 반환값을 완전히 무시하고, 그 결과 실제로는 메시지가 전송되지 않은 경우에도 사용자에게 메시지가 전송되었다고 알려준다.

#### [예제 4.21] 아웃컴 무시
```java
void sayHello(Channel channel) {
  sendMessage(channel, "hello");  // 성과 반환값이 무시된다.
  ui.setOutput("Hello sent");
}
```
일부 언어에서는 호출하는 쪽에서 함수의 반환값을 무시하면 컴파일러가 경고를 생성하도록 함수를 표시할 수 있다.
이름과 사용법은 언어마다 다르지만 몇 가지 예는 다음과 같다.
- 자바의 CheckReturnValue 애너테이션(javax.annotation 패키지)
- C#의 MustUseReturnValue 애너테이션(https://www.jetbrains.com/help/resharper)
- C++의 [[nodiscard]] 속성

만약 sendMessage() 함수가 이들 중 하나로 표시되었다면, 예제 4.21 코드에 대해서 개발자가 알아차릴 수 있도록 컴파일러는 경고 메시지를 보여줄 것이다.

다음 예제는 @CheckReturnValue 애너테이션을 sendMessage() 함수에 표시한 코드를 보여준다.

#### [예제 4.22] CheckReturnValue 애너테이션을 사용
```java
@CheckReturnValue  // 호출하는 쪽에서 함수의 반환값을 무시하며 안 된다는 것을 나타낸다.
Boolean sendMessage(Channel channel, String message) {
  ...
}
```
예제 4.21 코드의 작성자는 컴파일러 경고를 알아차리고 아웃컴을 처리한 이전 버전과 같은 코드로 수정할 것이다.

#### [예제 4.23] 반환값의 강제적 확인
```java
void sayHello(Channel channel) {
  if (sendMessage(channel, "hello")) {
    ui.setOutput("Hello sent");  // 성공한 경우 처리
  } else {
    ui.setError("Unable to send hello");
  }
}
```

## 7. 암시적 방법: 프로미스 또는 퓨처
비동기적으로 실행하는 코드를 작성할 때 **프로미스**(promise)나 **퓨처**(future)(혹은 이와 동등한 개념)를 반환하는 함수를 작성하는 것이 일반적이다.
(전부는 아니지만) 많은 언어에서 프로미스나 퓨처는 오류 상태도 전달할 수 있다.

프로미스나 퓨처를 사용할 때 일반적으로 오류 처리를 강제로 해야 하는 것은 아니고,
해당 함수에 대한 코드 계약의 세부 조항을 잘 알지 못하면 오류 처리 코드를 추가로 작성해야 한다는 것을 모를 수 있다.
따라서 프로미스나 퓨처를 사용한 오류 전달은 암시적인 방법이다.

#### [비동기적?]
동기적 프로세스는 작업을 한 번에 하나씩 순차적으로 수행하는 것을 말한다. 이전 작업이 완전히 완료되기 전까지는 다음 작업이 시작되지 않는다.
비동기적 프로세스는 다른 작업이 끝나기를 기다리는 동안 다른 작업을 수행할 수 있다는 것을 의미한다.

(응답을 반환하는 서버처럼) 코드가 어떤 일이 일어나기를 기다려야 할 때 비동기적으로 작성하는 것이 일반적이다.
서버로부터 응답을 기다리는 동안 코드는 다른 작업을 수행할 수 있다.

대부분의 프로그래밍 언어는 비동기적으로 코드를 실행하는 방법을 제공한다.
정확히 어떻게 하는지는 언어마다 다르기 때문에 자신이 사용하는 언어에 대해 그 내용을 찾아볼 가치가 있다.
다음 코드 예제에서 사용하는 비동기 함수와 프로미스는 자바스크립트와 비슷하다.
이것에 아직 익숙하지 않고 더 자세한 내용을 알고 싶다면 예제와 함께 설명이 잘되어 있는 async function 문서(https://mng.bz/w0wW)를 참고하기 바란다.

### 프로미스를 이용한 전달
예제 4.24 코드에는 getSquareRoot() 함수가 프로미스를 반환하고 실행하기 전에 1초를 기다리는 비동기 함수로 작성되어 있다.
함수 안에서 오류가 발생하면 프로미스는 **거부**(rejected)된다. 그렇지 않으면 프로미스는 반환값과 함께 **이행**(fulfilled)된다.

#### [예제 4.24] 비동기 함수
```java
class NegativeNumberError extends Error {  // 특정 유형의 오류임을 나타내는 클래스
  ...
}

Promise<Double> getSquareRoot(Double value) async {  // async는 이 함수가 비동기적임을 표시한다.
  await Timer.wait(Duration.ofSeconds(1));  // 실제 실행하기 전 1초를 기다린다.
  if (value < 0.0) {
    throw new NegativeNumberError(value);  // 함수 내에서 오류를 발생하고 프로미스는 거부된다.
  }
  return Math.sqrt(value);  // 값을 반환하면 프로미스는 이행된다.
}
```

### 프로미스 처리
예제 4.25 코드는 getSquareRoot()의 비동기 버전을 호출하는 displaySquareRoot() 함수를 보여준다.
getSquareRoot()에 의해 반환된 프로미스는 콜백을 설정하는 데 사용할 수 있는 두 가지 멤버 함수를 가지고 있다.
then() 함수는 프로미스가 이행되면 호출되는 콜백 기능을 설정하기 위해 사용하고, catch() 함수는 프로미스가 거부되면 호출되는 콜백을 설정하기 위해 사용한다.

#### [예제 4.25] 프로미스의 사용
```java
void displaySquareRoot() {
  getSquareRoot(ui.getInputNumber())
      .then(squareRoot ->  // then() 콜백은 프로미스가 이행되면 호출된다.
          ui.setOutput("Square root is: " + squareRoot))
      .catch(error ->  // catch() 콜백은 프로미스가 거부되면 호출된다.
          ui.setError("An error occured: " + error.toString()));
}
```

### 왜 프로미스는 암묵적인 오류 전달 기법인가
오류가 발생하고 프로미스가 거부될 수 있음을 알려면 프로미스를 생성하는 함수의 세부 조항이나 구현 세부 사항을 확인해야 한다.
이 내용을 모르면 프로미스의 사용자는 잠재적인 오류 상태를 쉽게 알 수 없으며, then() 함수를 통해서만 콜백을 제공할 것이다.
catch() 함수를 통해 콜백이 제공되지 않으면, 오류는 일부 상위 수준의 오류 처리 코드에 의해 포착되거나 완전히 눈에 띄지 않을 수 있다(언어와 설정에 따라 달라짐).

프로미스와 퓨처는 비동기 함수로부터 값을 반환하는 훌륭한 방법이다.
그러나 호출하는 쪽에서는 잠재적인 오류 시나리오를 완전히 알지 못하기 때문에 프로미스나 퓨처를 사용하는 것은 오류를 알리는 암시적인 방법이 된다.

### 프로미스를 명시적으로 만들기
프로미스나 퓨처를 반환할 때 명시적 오류 전달 기법으로 사용하려면, 리절트 유형의 프로미스를 반환하는 것이 한 가지 방법일 수 있다.
이렇게 하면 getSquareRoot() 기능은 다음 예제 코드와 같을 것이다. 이것은 유용한 기술이지만, 코드가 복잡해지기 때문에 모든 사람이 다 이렇게 사용하고자 하지는 않을 것이다.

#### [예제 4.26] 리절트 유형 프로미스
```java
Promise<Result<Double, NegativeNumberError>> getSquareRoot(  // 반환 유형이 상당히 복잡하다.
    Double value) async {
  await Timer.wait(Duration.ofSeconds(1));
  if (value < 0.0) {
    return Result.ofError(new NegativeNumberError(value));
  }
  return Result.ofValue(Math.sqrt(value));
}
```

## 8. 암시적 방법: 매직값 반환
**매직값**(magic value)(또는 오류 코드)은 함수의 정상적인 반환 유형에 적잡하지만 특별한 의미를 부여하는 값이다.
매직값이 반환될 수 있다는 것을 알려면 문서나 코드를 읽어야 한다. 따라서 이것은 암시적 오류 전달 기법이다.

매직값을 사용하여 오류를 알리는 일반적인 방법은 -1을 반환하는 것이다. 다음 예제는 이에 대한 getSquareRoot() 함수를 보여준다.

#### [예제 4.27] 매직값 반환
```java
// 음숫값이 입력으로 제공되면 -1을 반환한다. ---> 함수가 -1을 반환할 수 있음을 알리는 주석문
Double getSquareRoot(Double value) {
  if (value < 0.0) {
    return -1.0;  // 오류가 발생하면 -1이 반환된다.
  }
  return Math.sqrt(value);
}
```
매직값은 코드 계약의 명백한 부분을 통해 호출하는 쪽에 알릴 수 없어서 예상을 벗어나는 결과를 가져올 수도 있고 버그로 이어질 수도 있다.
매직값이 일으킬 수 있는 문제들은 6장에서 자세히 살펴보기 때문에 여기서는 자세히 논의하지 않는다.
그러나 이 장에서 기억해야 할 중요한 점은 매직값은 오류를 알리는 좋은 방법이 아니라는 것이다.
